### ISSUE TITLE
Generated Webhook outputs error.

### ISSUE THREAD

**Issue by kevin-og** [GezimSejdiu/Rocket.Chat-Trello-Integration#2] opened 2018-02-26 21:51 UTC
{"success":false,"error":"error-running-script"} at step ix

**Comment by kevin-og** [comment] 2018-02-26 23:17
`var data=request.content.action.data;var attachment_name=data.attachment.name;var attachment_url=data.attachment.url;var attachment_preview_url=data.attachment.previewUrl;message_text="New attachment added to card \"["+card_name+"](https://trello.com/c/"+card_link+")\"\n **["+attachment_name+"]("+attachment_url+")**"}if(url==undefined||message_text==author_name)return;return{content:{alias:author_name,icon_url:user_avatar,"attachments":[{"color":"#FF0000","title":request.content.model.name,"title_link":request.content.model.shortUrl,"text":message_text+"\n"+attachment_text}]}}};return Script}();
rocketchat_logger rocketchat_logger.js:375 Integrations ➔ Incoming WebHook.error [Stack:]
rocketchat_logger rocketchat_logger.js:375 Integrations ➔ Incoming WebHook.error   TypeError: Cannot read property 'shortUrl' of undefined
      at Script.process_incoming_request (script.js:1:420)
      at evalmachine.<anonymous>:1:8
      at ContextifyScript.Script.runInNewContext (vm.js:18:15)
      at Object.exports.runInNewContext (vm.js:49:17)
      at Object.executeIntegrationRest [as action] (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_integrations.js:2789:20)
      at Route.share.Route.Route._callEndpoint (/home/ubuntu/Rocket.Chat/programs/server/packages/nimble_restivus.js:361:32)
      at /home/ubuntu/Rocket.Chat/programs/server/packages/nimble_restivus.js:250:33
      at packages/simple_json-routes.js:98:9
`

**Comment by iooner** [comment] 2018-02-27 10:34
i've the same problem here.
{"success":false,"error":"error-running-script"}

**Comment by GezimSejdiu** [comment] 2018-03-02 12:20
Hi @kevin-og , hi @iooner ,
many thanks for using Trello Integration for Rocket.Chat.

The error seems to be related with #1 which mean you should first add an integration without js script because trello sends first request (head) without any json data.

Let me know if the issue still persists.
**Update**: 
I just tested it and it works as intended : 
![image](https://user-images.githubusercontent.com/5259296/36898803-a18d80fe-1e1c-11e8-9371-e3cf1ba84d53.png)


Best regards,

**Comment by GezimSejdiu** [comment] 2018-03-05 12:53
Hi @kevin-og , @iooner ,
any news about the issue?

Please, could you let me know if the issue still persists or shall I consider this issue as resolved?

Best regards,

**Comment by GezimSejdiu** [comment] 2018-03-15 13:37
I'm going to close this issue for now, since it is working at my end. Feel free to open it if necessary!

Many thanks for your valuable feedback!

**Closed as completed by GezimSejdiu** 2018-03-15 13:37 UTC
